# Generated by Django 3.1.7 on 2021-07-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(editable=False, max_length=11, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=120)),
                ('student_class', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
